# ----------------------- #
#      Main Configs       #
# ----------------------- #
auto: true
layouts:     ./_layouts
baseurl: /
# baseurl: http://www.designtoday.info/altmetric/conf/

# ----------------------- #
#      layout             #
# ----------------------- #
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"