# ----------------------- #
#      Main Configs       #
# ----------------------- #
auto: true
layouts:     ./_layouts
baseurl: http://0.0.0.0:4000/

# ----------------------- #
#      layout             #
# ----------------------- #
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"