# ----------------------- #
#      Main Configs       #
# ----------------------- #
auto: true
layouts:     ./_layouts
baseurl: /

# ----------------------- #
#      layout             #
# ----------------------- #
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"